version: "3.8"

services:
  # Node.js application
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/instagram
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

  # MongoDB service
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
